
export const FETCH_RANDOM_MEAL = "FETCH_RANDOM_MEAL";
export const FETCH_MEALS_FROM_CATEGORY = "FETCH_MEALS_FROM_CATEGORY";
export const FETCH_CUISINE_LIST = "FETCH_CUISINE_LIST";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";